triggers:
- envs: []
  last_enabled_at: 2024-02-05 08:31:13.336107
  name: green_taxi_etl
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-06 05:00:00
  status: active
  variables: {}
